name: Run Jest Tests

on:
    push:

env:
    NODE_ENV: 'production'

jobs:
    run-jest:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x, 12.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.JS ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: npm install

            - name: Run Jest Tests
              run: npm run test
